apiVersion: angi.my.domain/v1alpha1
kind: MyAppResource
metadata:
  name: test-resource
spec:
  replicaCount: 2
  resources:
    memoryLimit: 64Mi
    cpuRequest: 100m
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: latest
  ui:
    color: "#34577c"
    message: "some string"
  redis:
    enabled: true